(()=>{
'use strict';
const ROOT=document.querySelector('#app');
const KEY='bell-beneath-ash-p01b';
const SLOTS=['Weapon','Head','Armor','Charm'];
const SETS={
  'Ashen Pilgrim':{two:'+4 ATK to equipped Hunters',four:'+12 starting Resolve'},
  'Mourning Watch':{two:'+18 max HP to equipped Hunters',four:'8% incoming damage reduction'}
};
const HUNTER_BASE=[
  {id:'vanguard',name:'Vanguard',role:'Frontline',hp:170,atk:16,row:'front'},
  {id:'duelist',name:'Duelist',role:'Striker',hp:116,atk:24,row:'front'},
  {id:'physician',name:'Physician',role:'Support',hp:126,atk:12,row:'back'}
];
const REGIONS=[
  {name:'Forsaken Farmstead',short:'FARMSTEAD',kind:'farm',reward:{coin:28,iron:18,salvage:3},enemies:[['Carrion Scavenger',58,11,'front','feral'],['Ash Hound',44,12,'front','feral'],['Farmstead Lurker',52,10,'back','lurker']]},
  {name:'Hollow Causeway',short:'CAUSEWAY',kind:'causeway',reward:{coin:38,iron:17,salvage:7},enemies:[['Road Reaver',86,15,'front','reaver'],['Road Reaver',78,14,'front','reaver'],['Ashbound Rifleman',66,18,'back','rifleman'],['Bridge Spotter',54,11,'back','spotter']]},
  {name:'Saint Orra Chapel',short:'SAINT ORRA',kind:'chapel',reward:{coin:48,iron:19,salvage:9},enemies:[['Reliquary Husk',128,18,'front','husk'],['Reliquary Husk',112,17,'front','husk'],['Chapel Thrall',80,17,'front','thrall'],['Bell Hand',70,20,'back','bell']]},
  {name:'Penitent Warden',short:'WARDEN',kind:'warden',reward:{coin:90,iron:24,salvage:14},enemies:[['Penitent Warden',410,28,'front','warden'],['Bellbound Servitor',118,18,'front','servitor'],['Bellbound Servitor',118,18,'front','servitor']]}
];
const EVENTS=[
  {title:'THE BURIED HOUSE',text:'A farmhouse roof cuts through the ash. A broken window opens into the buried rooms below.',risk:'SEARCH BELOW',safe:'MARK THE SITE',resource:'salvage'},
  {title:'THE HANGING BUS',text:'A transit carriage hangs over the collapsed road. A military case is visible behind the shattered glass.',risk:'CROSS INTO IT',safe:'TAKE THE LONG ROAD',resource:'iron'},
  {title:'THE UNLIT SHRINE',text:'Three black candles stand untouched behind Saint Orra. A sealed reliquary rests beneath them.',risk:'BREAK THE SEAL',safe:'LEAVE IT CLOSED',resource:'coin'}
];
function fresh(){return {
  version:3,screen:'title',started:false,tutorial:0,coin:90,iron:12,salvage:0,
  buildings:{hall:1,forge:1,infirmary:1,tower:1},hunters:HUNTER_BASE.map(x=>({...x,lv:1,xp:0})),
  clears:[0,0,0,0],inventory:[],equipped:{},crafted:0,eventCount:0,preparedKit:false,
  lastDrops:[],lastResult:null,wardenDefeated:false,selectedHunter:'Vanguard'
}}
let G=load();let battle=null;let timer=null;let pendingRegion=null;let sheet=null;
function load(){try{const v=JSON.parse(localStorage.getItem(KEY)||'null');return v&&v.version===3?v:fresh()}catch{return fresh()}}
function save(){localStorage.setItem(KEY,JSON.stringify(G))}
function reset(){localStorage.removeItem(KEY);G=fresh();battle=null;pendingRegion=null;sheet=null;render()}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function objective(){
  if(G.clears[0]<1)return {n:1,title:'Open the Western Road',body:'Clear Forsaken Farmstead.',action:'MARCHES',screen:'map'};
  if(countEquipped()<1)return {n:2,title:'Arm a Hunter',body:'Equip one recovered item.',action:'INVENTORY',screen:'inventory'};
  if(G.buildings.hall<2)return {n:3,title:'Strengthen the Hunter Hall',body:'Upgrade the Hall to Level 2.',action:'HUNTER HALL',sheet:'hall'};
  if(G.clears[1]<1)return {n:4,title:'Break the Causeway',body:'Clear Hollow Causeway.',action:'MARCHES',screen:'map'};
  if(G.crafted<1)return {n:5,title:'Reconstruct the March',body:'Forge one item from recovered material.',action:'FORGE',sheet:'forge'};
  if(G.clears[2]<1)return {n:6,title:'Silence Saint Orra',body:'Clear Saint Orra Chapel.',action:'MARCHES',screen:'map'};
  if(G.clears[3]<1)return {n:7,title:'The Bell Must Stop',body:'Defeat the Penitent Warden.',action:'MARCHES',screen:'map'};
  return {n:8,title:'The Western Road Holds',body:'The first March is secure. Continue hunting equipment and sets.'};
}
function regionOpen(i){if(i===0)return true;if(i===1)return G.clears[0]>0&&G.buildings.hall>=2;if(i===2)return G.clears[1]>0&&G.crafted>=1;if(i===3)return G.clears[2]>0;return false}
function countEquipped(){return Object.keys(G.equipped||{}).length}
function equipmentFor(name){return Object.values(G.equipped||{}).filter(i=>i.owner===name)}
function setCount(setName){return Object.values(G.equipped||{}).filter(i=>i.set===setName).length}
function itemMods(name){let atk=0,hp=0;for(const i of equipmentFor(name)){atk+=i.atk||0;hp+=i.hp||0}if(setCount('Ashen Pilgrim')>=2)atk+=4;if(setCount('Mourning Watch')>=2)hp+=18;return{atk,hp}}
function hunterStats(h){const m=itemMods(h.name);return{hp:h.hp+(h.lv-1)*8+m.hp,atk:h.atk+(h.lv-1)*3+m.atk}}
function header(){return `<header class="hud"><button class="brand" data-go="enclave"><span>THE BELL BENEATH ASH</span><small>ASHEN MARCHES · P0.1B</small></button><div class="resources"><span>◈ ${G.coin}</span><span>⚒ ${G.iron}</span><span>⌁ ${G.salvage}</span></div></header>`}
function nav(){const items=[['enclave','ENCLAVE'],['hunters','HUNTERS'],['map','MARCHES'],['inventory','LOOT']];return `<nav class="bottomnav">${items.map(([s,l])=>`<button data-go="${s}" class="${G.screen===s?'active':''}"><i>${s==='enclave'?'⌂':s==='hunters'?'♜':s==='map'?'✦':'◆'}</i><span>${l}</span></button>`).join('')}</nav>`}
function directive(){const o=objective();if(o.n===8)return `<section class="directive complete"><small>REGIONAL STATUS</small><b>${o.title}</b><span>${o.body}</span></section>`;return `<section class="directive"><small>DIRECTIVE ${o.n}/7</small><b>${o.title}</b><span>${o.body}</span><button data-directive>GO</button></section>`}
function titleView(){return `<main class="titleview"><div class="titleart">${sceneSvg('title')}</div><div class="titlecopy"><small>ORIGINAL 2D GOTHIC STRATEGY RPG</small><h1>THE BELL<br>BENEATH ASH</h1><p>The old world is buried beneath a permanent fall of ash. Your Enclave survives by sending Hunters beyond the walls to reclaim roads, weapons and the things people left behind.</p><p class="muted">Something in the western March is ringing a bell that no living hand should be able to reach.</p><button class="primary huge" data-begin>${G.started?'CONTINUE':'BEGIN THE MARCH'}</button></div></main>`}
function enclaveView(){return `<main class="gameview enclaveview"><section class="worldscene">${sceneSvg('enclave')}<button class="hotspot hall" data-building="hall"><b>HUNTER HALL</b><span>LV ${G.buildings.hall}</span></button><button class="hotspot forge" data-building="forge"><b>FORGE</b><span>LV ${G.buildings.forge}</span></button><button class="hotspot infirmary" data-building="infirmary"><b>INFIRMARY</b><span>LV ${G.buildings.infirmary}</span></button><button class="hotspot tower" data-building="tower"><b>SCOUT TOWER</b><span>LV ${G.buildings.tower}</span></button><button class="hotspot store" data-go="inventory"><b>STOREHOUSE</b><span>${G.inventory.length} ITEMS</span></button><button class="hotspot guild locked"><b>GUILD HALL</b><span>SEALED</span></button></section>${directive()}${G.wardenDefeated?'<div class="victorystrip">THE PENITENT WARDEN IS DEAD · WESTERN ROAD SECURED</div>':''}</main>`}
function huntersView(){return `<main class="gameview huntersview"><section class="hunterstage">${sceneSvg('hall')}<div class="hunterrow">${G.hunters.map(h=>{const s=hunterStats(h);return `<button class="hunterportrait ${G.selectedHunter===h.name?'selected':''}" data-hunter="${h.name}">${hunterSvg(h.id)}<b>${h.name}</b><span>${h.role}</span><small>LV ${h.lv} · HP ${s.hp} · ATK ${s.atk}</small></button>`}).join('')}</div></section><section class="compactpanel"><div><small>FORMATION</small><b>${G.buildings.hall>=3?'5 HUNTERS':G.buildings.hall>=2?'4 HUNTERS':'3 HUNTERS'}</b><span>${G.buildings.hall>=2?'Enclave Guard active':'Upgrade Hunter Hall for support'}${G.buildings.hall>=3?' · March Scout active':''}</span></div><button data-building="hall">HALL LV ${G.buildings.hall}</button></section><section class="loadoutmini">${SLOTS.map(sl=>{const x=G.equipped[`${G.selectedHunter}:${sl}`];return `<button data-slot="${sl}"><small>${sl}</small><b>${x?esc(x.name):'EMPTY'}</b><span>${x?`+${x.atk||0} ATK${x.hp?` · +${x.hp} HP`:''}`:'Tap Loot to equip'}</span></button>`}).join('')}</section></main>`}
function mapView(){return `<main class="gameview mapview"><section class="marchmap">${sceneSvg('map')}<div class="route"></div>${REGIONS.map((r,i)=>`<button class="mapnode node${i} ${regionOpen(i)?'open':'closed'} ${G.clears[i]?'cleared':''}" data-region="${i}" ${regionOpen(i)?'':'disabled'}><i>${G.clears[i]?'✓':i===0?'⌂':i===1?'╫':i===2?'†':'♜'}</i><b>${regionOpen(i)?r.short:'UNKNOWN'}</b><span>${G.clears[i]?`${G.clears[i]} CLEAR${G.clears[i]>1?'S':''}`:regionOpen(i)?'OPEN':'FOG'}</span></button>`).join('')}</section><section class="mapintel"><div><small>SCOUT TOWER · LV ${G.buildings.tower}</small><b>${objective().title}</b><span>${objective().body}</span></div><button data-building="tower">INTEL</button></section></main>`}
function inventoryView(){const h=G.selectedHunter;return `<main class="gameview inventoryview"><section class="inventoryhead"><div><small>STOREHOUSE</small><h2>Recovered Equipment</h2><span>${G.inventory.length} items · ${countEquipped()} equipped</span></div><button data-building="forge">OPEN FORGE</button></section><section class="setbar"><div><b>Ashen Pilgrim</b><span>${setCount('Ashen Pilgrim')}/4 · 2PC ${setCount('Ashen Pilgrim')>=2?'ACTIVE':'LOCKED'} · 4PC ${setCount('Ashen Pilgrim')>=4?'ACTIVE':'LOCKED'}</span></div><div><b>Mourning Watch</b><span>${setCount('Mourning Watch')}/4 · 2PC ${setCount('Mourning Watch')>=2?'ACTIVE':'LOCKED'} · 4PC ${setCount('Mourning Watch')>=4?'ACTIVE':'LOCKED'}</span></div></section><section class="huntertabs">${G.hunters.map(x=>`<button class="${h===x.name?'active':''}" data-hunter="${x.name}">${x.name}</button>`).join('')}</section><section class="lootlist">${G.inventory.length?G.inventory.slice().sort((a,b)=>rarityRank(b.rarity)-rarityRank(a.rarity)||(b.atk||0)-(a.atk||0)).map(i=>itemRow(i,h)).join(''):'<div class="emptyloot">The shelves are empty. Enter the Marches.</div>'}</section></main>`}
function rarityRank(r){return {common:0,uncommon:1,rare:2,relic:3}[r]||0}
function itemRow(i,h){const eq=i.owner?`EQUIPPED · ${i.owner}`:'UNEQUIPPED';const set=i.set?` · ${i.set}`:'';return `<article class="lootrow rarity-${i.rarity}"><div class="itemicon">${slotIcon(i.slot)}</div><div class="itemcopy"><small>${i.rarity.toUpperCase()} · ${i.slot}${set}</small><b>${esc(i.name)}</b><span>${i.affix} · +${i.atk||0} ATK${i.hp?` · +${i.hp} HP`:''} · ${eq}</span></div><div class="itemactions"><button data-equip="${i.id}" data-owner="${h}">${i.owner===h?'EQUIPPED':`EQUIP → ${h}`}</button><button data-salvage="${i.id}" ${i.owner?'disabled':''}>SALVAGE</button></div></article>`}
function slotIcon(s){return s==='Weapon'?'⚔':s==='Head'?'◉':s==='Armor'?'⛨':'✦'}
function buildingSheet(kind){const lv=G.buildings[kind],names={hall:'Hunter Hall',forge:'Forge',infirmary:'Infirmary',tower:'Scout Tower'},desc={hall:'Expands the expedition formation. Lv2 adds an Enclave Guard; Lv3 adds a March Scout.',forge:'Turns salvage into targeted gear. Higher levels improve crafted rarity.',infirmary:'Reduces expedition recovery costs and improves Field Treatment.',tower:'Reveals threat information and improves field discovery outcomes.'};let action='';if(kind==='forge')action=`<div class="sheetaction"><b>RECONSTRUCT EQUIPMENT</b><span>14 Iron + 8 Salvage · guaranteed uncommon+ item</span><button class="primary" data-craft ${G.iron<14||G.salvage<8?'disabled':''}>CRAFT</button></div>`;if(kind==='infirmary')action=`<div class="sheetaction"><b>FIELD KIT</b><span>18 Coin · next combat starts with Guard + Resolve</span><button class="primary" data-kit ${G.preparedKit||G.coin<18?'disabled':''}>${G.preparedKit?'PACKED':'PREPARE'}</button></div>`;const cost=lv===1?20:40;return `<div class="sheetback" data-close></div><aside class="sheet"><button class="sheetclose" data-close>×</button><small>ENCLAVE FACILITY</small><h2>${names[kind]} · Lv ${lv}</h2><p>${desc[kind]}</p>${action}${lv<3?`<div class="sheetaction"><b>UPGRADE TO LV ${lv+1}</b><span>${cost} Iron</span><button class="primary" data-upgrade="${kind}" ${G.iron<cost?'disabled':''}>UPGRADE</button></div>`:'<div class="maxed">MAXIMUM PROTOTYPE LEVEL</div>'}</aside>`}
function eventView(){const e=EVENTS[pendingRegion];return `<main class="eventview">${header()}<section class="eventart">${sceneSvg(REGIONS[pendingRegion].kind)}</section><section class="eventcopy"><small>FIELD DISCOVERY · ${REGIONS[pendingRegion].name}</small><h1>${e.title}</h1><p>${e.text}</p><div class="eventchoices"><button class="primary" data-event="risk">${e.risk}</button><button data-event="safe">${e.safe}</button></div></section></main>`}
function battleView(){if(!battle)return mapView();const r=REGIONS[battle.region];return `<main class="battleview"><section class="battlescene zone-${r.kind}">${sceneSvg(r.kind)}<div class="enemyformation">${battle.enemies.map((e,i)=>unitEnemy(e,i)).join('')}</div><div class="allyformation">${battle.party.map((u,i)=>unitAlly(u,i)).join('')}</div></section><section class="combatbar"><div class="combatmeta"><div><small>${r.name.toUpperCase()}</small><b>TURN ${battle.turn}</b></div><div class="resolve"><span>RESOLVE ${Math.floor(battle.resolve)}/100</span><i><em style="width:${battle.resolve}%"></em></i></div></div><div class="abilities"><button data-ability="focus" ${battle.resolve<30?'disabled':''}>FOCUS<small>30</small></button><button data-ability="sever" ${battle.resolve<40||!living('Duelist')?'disabled':''}>SEVER<small>40</small></button><button data-ability="guard" ${battle.resolve<25||!living('Vanguard')?'disabled':''}>BRACE<small>25</small></button><button data-ability="heal" ${battle.resolve<35||!living('Physician')?'disabled':''}>TREAT<small>35</small></button></div><button class="retreat" data-retreat>RETREAT</button></section></main>`}
function unitEnemy(u,i){return `<button class="battleunit enemy ${u.hp<=0?'down':''} ${battle.target===i?'target':''}" data-target="${i}" ${u.hp<=0?'disabled':''}>${enemySvg(u.cls)}<b>${esc(u.name)}</b><div class="unitbar"><i style="width:${100*u.hp/u.max}%"></i></div><small>${u.hp}/${u.max}${statusText(u)}</small></button>`}
function unitAlly(u,i){return `<div class="battleunit ally ${u.hp<=0?'down':''}">${hunterSvg(u.id||'guard')}<b>${u.name}</b><div class="unitbar"><i style="width:${100*u.hp/u.max}%"></i></div><small>${u.hp}/${u.max}${statusText(u)}</small></div>`}
function statusText(u){const a=[];if(u.status.bleed)a.push('BLEED');if(u.status.mark)a.push('MARKED');if(u.status.broken)a.push('BROKEN');return a.length?' · '+a.join(' · '):''}
function resultView(){const x=G.lastResult;if(!x)return mapView();return `<main class="resultview">${header()}<section class="resultart">${sceneSvg(x.boss?'warden':'result')}</section><section class="resultcopy"><small>${x.boss?'REGIONAL THREAT BROKEN':'EXPEDITION VICTORY'}</small><h1>${x.boss?'THE BELL FALLS SILENT':REGIONS[x.region].name+' CLEARED'}</h1><div class="rewardchips"><span>◈ +${x.reward.coin}</span><span>⚒ +${x.reward.iron}</span><span>⌁ +${x.reward.salvage}</span></div><div class="droppreview">${G.lastDrops.map(i=>`<div class="drop rarity-${i.rarity}">${slotIcon(i.slot)}<span><small>${i.rarity.toUpperCase()}</small><b>${esc(i.name)}</b></span></div>`).join('')}</div><button class="primary huge" data-secure>SECURE ${G.lastDrops.length} DROPS</button></section></main>`}
function render(){clearTimeout(timer);let html=G.screen==='title'?titleView():G.screen==='event'?eventView():G.screen==='battle'?battleView():G.screen==='result'?resultView():`${header()}${G.screen==='enclave'?enclaveView():G.screen==='hunters'?huntersView():G.screen==='map'?mapView():inventoryView()}${nav()}`;ROOT.innerHTML=html+(sheet?buildingSheet(sheet):'');bind();if(G.screen==='battle'&&battle&&!battle.paused)timer=setTimeout(()=>tick(),720)}
function bind(){ROOT.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));ROOT.querySelector('[data-begin]')?.addEventListener('click',()=>{G.started=true;G.screen='enclave';G.tutorial=1;save();render()});ROOT.querySelectorAll('[data-building]').forEach(b=>b.onclick=()=>{sheet=b.dataset.building;render()});ROOT.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{sheet=null;render()});ROOT.querySelector('[data-directive]')?.addEventListener('click',()=>{const o=objective();if(o.screen)go(o.screen);else if(o.sheet){sheet=o.sheet;render()}});ROOT.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>depart(+b.dataset.region));ROOT.querySelectorAll('[data-hunter]').forEach(b=>b.onclick=()=>{G.selectedHunter=b.dataset.hunter;save();render()});ROOT.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>equip(+b.dataset.equip,b.dataset.owner));ROOT.querySelectorAll('[data-salvage]').forEach(b=>b.onclick=()=>salvage(+b.dataset.salvage));ROOT.querySelector('[data-upgrade]')?.addEventListener('click',e=>upgrade(e.currentTarget.dataset.upgrade));ROOT.querySelector('[data-craft]')?.addEventListener('click',craft);ROOT.querySelector('[data-kit]')?.addEventListener('click',packKit);ROOT.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>resolveEvent(b.dataset.event==='risk'));ROOT.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>{battle.target=+b.dataset.target;render()});ROOT.querySelectorAll('[data-ability]').forEach(b=>b.onclick=()=>ability(b.dataset.ability));ROOT.querySelector('[data-retreat]')?.addEventListener('click',retreat);ROOT.querySelector('[data-secure]')?.addEventListener('click',()=>{G.screen='inventory';save();render()})}
function go(s){sheet=null;if(['enclave','hunters','map','inventory'].includes(s)){G.screen=s;save();render()}}
function upgrade(k){const lv=G.buildings[k],cost=lv===1?20:40;if(lv>=3||G.iron<cost)return;G.iron-=cost;G.buildings[k]++;save();render()}
function packKit(){if(G.coin<18||G.preparedKit)return;G.coin-=18;G.preparedKit=true;save();render()}
function craft(){if(G.iron<14||G.salvage<8)return;G.iron-=14;G.salvage-=8;G.crafted++;G.inventory.push(makeItem(Math.max(1,G.clears[1]?1:0),{minimum:'uncommon',crafted:true}));save();render()}
function equip(id,owner){const i=G.inventory.find(x=>x.id===id);if(!i)return;for(const [k,v] of Object.entries(G.equipped)){if(v.id===id){delete G.equipped[k]}}if(i.owner)delete i.owner;const key=`${owner}:${i.slot}`,old=G.equipped[key];if(old){const oi=G.inventory.find(x=>x.id===old.id);if(oi)delete oi.owner}i.owner=owner;G.equipped[key]=i;save();render()}
function salvage(id){const i=G.inventory.find(x=>x.id===id);if(!i||i.owner)return;G.salvage+=i.rarity==='relic'?12:i.rarity==='rare'?7:i.rarity==='uncommon'?4:2;G.inventory=G.inventory.filter(x=>x.id!==id);save();render()}
function depart(i){if(!regionOpen(i))return;pendingRegion=i;const eventAllowed=i<3&&G.clears[0]>0;const chance=.28+.1*G.buildings.tower;if(eventAllowed&&Math.random()<chance){G.screen='event';save();render()}else startBattle(i,{})}
function resolveEvent(risk){const i=pendingRegion,e=EVENTS[i],tower=G.buildings.tower,infirmary=G.buildings.infirmary;G.eventCount++;let carry={};if(risk){if(Math.random()<.55+.08*tower){const n=6+i*2+tower;if(e.resource==='coin')G.coin+=n*4;if(e.resource==='iron')G.iron+=n;if(e.resource==='salvage')G.salvage+=n;carry.edge=8+tower*3}else carry.hurt=Math.max(5,18-infirmary*4)}else carry.edge=3+tower;save();startBattle(i,carry)}
function makeParty(){const p=G.hunters.map(h=>{const s=hunterStats(h);return{id:h.id,name:h.name,role:h.role,row:h.row,hp:s.hp,max:s.hp,atk:s.atk,status:{},core:true}});if(G.buildings.hall>=2)p.push({id:'guard',name:'Enclave Guard',role:'Auxiliary',row:'front',hp:118,max:118,atk:13,status:{},core:false});if(G.buildings.hall>=3)p.push({id:'scout',name:'March Scout',role:'Auxiliary',row:'back',hp:88,max:88,atk:16,status:{},core:false});return p}
function startBattle(i,carry={}){pendingRegion=null;const enemies=REGIONS[i].enemies.map((x,n)=>({name:x[0],hp:x[1],max:x[1],atk:x[2],row:x[3],cls:x[4],status:{},id:n})),party=makeParty();if(carry.edge)enemies[0].hp=Math.max(1,enemies[0].hp-carry.edge);if(carry.hurt)party.filter(x=>x.row==='front').forEach(x=>x.hp=Math.max(1,x.hp-carry.hurt));battle={region:i,enemies,party,target:0,resolve:30,turn:0,guard:0,dread:0,paused:false};if(setCount('Ashen Pilgrim')>=4)battle.resolve+=12;if(G.preparedKit){battle.guard=2+G.buildings.infirmary;battle.resolve=clamp(battle.resolve+8,0,100);G.preparedKit=false}G.screen='battle';save();render()}
function alive(a){return a.filter(x=>x.hp>0)}
function living(name){return battle?.party.some(x=>x.name===name&&x.hp>0)}
function targetEnemy(){if(!battle)return null;if(battle.enemies[battle.target]?.hp>0)return battle.enemies[battle.target];battle.target=battle.enemies.findIndex(x=>x.hp>0);return battle.enemies[battle.target]}
function hit(u,d){u.hp=Math.max(0,u.hp-Math.max(1,Math.round(d)))}
function tick(manual=false){if(!battle||G.screen!=='battle')return;clearTimeout(timer);const b=battle;b.turn++;b.party.forEach(u=>{if(u.hp>0&&u.status.bleed){hit(u,3);u.status.bleed--}if(u.status.mark)u.status.mark--});b.enemies.forEach(u=>{if(u.hp>0&&u.status.bleed){hit(u,6);u.status.bleed--}if(u.status.broken)u.status.broken--});let t=targetEnemy();for(const u of alive(b.party)){if(!t||t.hp<=0)t=targetEnemy();if(!t)break;const broken=t.status.broken?1.25:1,armor=t.cls==='husk'&&!t.status.broken?.9:1;hit(t,(u.atk*.34+Math.random()*5)*broken*armor)}if(!alive(b.enemies).length)return victory();const front=alive(b.party.filter(x=>x.row==='front')),back=alive(b.party.filter(x=>x.row==='back'));for(const e of alive(b.enemies)){const pool=e.row==='back'&&Math.random()<.32&&back.length?back:(front.length?front:alive(b.party));if(!pool.length)break;const x=pool[Math.floor(Math.random()*pool.length)],marked=x.status.mark?1.22:1,guard=b.guard?0.56:1,watch=setCount('Mourning Watch')>=4?.92:1,execute=e.cls==='reaver'&&x.hp/x.max<.4?1.22:1;hit(x,(e.atk*.55+Math.random()*4)*marked*guard*watch*execute);if(e.cls==='feral'&&Math.random()<.18)x.status.bleed=2;if(['rifleman','spotter'].includes(e.cls)&&Math.random()<.22)x.status.mark=2;if(e.cls==='bell'&&b.turn%4===0){b.dread=2;x.status.mark=2}if(e.cls==='warden'&&b.turn%3===0){b.dread=2;x.status.mark=2}if(e.cls==='servitor'&&b.turn%5===0){const w=b.enemies.find(y=>y.cls==='warden'&&y.hp>0);if(w)w.hp=Math.min(w.max,w.hp+6)}}if(b.turn%3===0&&living('Physician')){const w=alive(b.party).sort((a,c)=>a.hp/a.max-c.hp/c.max)[0];if(w)w.hp=Math.min(w.max,w.hp+6+G.buildings.infirmary*2)}if(b.guard)b.guard--;if(b.dread)b.dread--;b.resolve=clamp(b.resolve+(b.dread?6:11),0,100);if(!alive(b.party).length)return defeat();if(!manual)render()}
function ability(a){if(!battle)return;const b=battle,t=targetEnemy(),w=alive(b.party).sort((x,y)=>x.hp/x.max-y.hp/y.max)[0];if(a==='focus'&&b.resolve>=30&&t){b.resolve-=30;hit(t,36+Math.random()*12)}else if(a==='sever'&&b.resolve>=40&&t&&living('Duelist')){b.resolve-=40;hit(t,45);t.status.bleed=3;t.status.broken=2}else if(a==='guard'&&b.resolve>=25&&living('Vanguard')){b.resolve-=25;b.guard=3}else if(a==='heal'&&b.resolve>=35&&w&&living('Physician')){b.resolve-=35;w.hp=Math.min(w.max,w.hp+40+G.buildings.infirmary*5);w.status.bleed=0;w.status.mark=0}if(!alive(b.enemies).length)return victory();render()}
function retreat(){clearTimeout(timer);battle=null;G.screen='map';save();render()}
function gainXP(region){for(const h of G.hunters){h.xp+=12+region*7;while(h.lv<10&&h.xp>=h.lv*48){h.xp-=h.lv*48;h.lv++}}}
function victory(){clearTimeout(timer);const i=battle.region,boss=i===3;G.clears[i]++;const r=REGIONS[i].reward;G.coin+=r.coin;G.iron+=r.iron;G.salvage+=r.salvage;gainXP(i);const count=boss?5:3+(Math.random()<.35?1:0),drops=[];for(let n=0;n<count;n++)drops.push(makeItem(i,{boss,n}));if(boss){drops[0]=makeItem(3,{boss:true,relic:true,name:'Warden’s Penitent Blade',slot:'Weapon',set:'Ashen Pilgrim'});G.wardenDefeated=true}G.inventory.push(...drops);G.lastDrops=drops;G.lastResult={region:i,boss,reward:r,survivors:alive(battle.party).length,total:battle.party.length};battle=null;G.screen='result';save();render()}
function defeat(){clearTimeout(timer);const i=battle.region;G.coin=Math.max(0,G.coin-8);battle=null;G.screen='map';save();render()}
let itemId=1;
function makeItem(region,opt={}){const slots=SLOTS,slot=opt.slot||slots[Math.floor(Math.random()*slots.length)],roll=Math.random();let rarity=opt.relic?'relic':roll>.92?'relic':roll>.68?'rare':roll>.27?'uncommon':'common';if(opt.minimum==='uncommon'&&rarity==='common')rarity='uncommon';const base={common:3,uncommon:5,rare:8,relic:12}[rarity]+region*2+(opt.crafted?1:0);const hp=slot==='Armor'||slot==='Head'?({common:0,uncommon:4,rare:8,relic:14}[rarity]||0):0;const set=opt.set!==undefined?opt.set:(Math.random()<.27?(Math.random()<.58?'Ashen Pilgrim':'Mourning Watch'):null);const names={Weapon:['Grave-Iron Blade','Blackroad Cleaver','Cinder Pike','Pilgrim Severance'],Head:['Ash Hood','Watchman Visor','Reliquary Helm','Mourning Cowl'],Armor:['Road Mantle','Graveplate Coat','Ash-Walker Harness','Watchman Plate'],Charm:['Censer Shard','Bellbone Talisman','Black Salt Reliquary','Pilgrim Token']};return{id:Date.now()+itemId+++(Math.random()),name:opt.name||names[slot][Math.floor(Math.random()*names[slot].length)],slot,rarity,atk:base,hp,set,affix:['Keen','Stalwart','Hollow','Vicious','Consecrated','Ashbound'][Math.floor(Math.random()*6)]}}
function sceneSvg(kind){const chapel=kind==='chapel'||kind==='warden'||kind==='title',farm=kind==='farm',cause=kind==='causeway',enclave=kind==='enclave'||kind==='hall',map=kind==='map';return `<svg viewBox="0 0 800 500" class="scene" preserveAspectRatio="xMidYMid slice"><defs><linearGradient id="sky-${kind}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#53636c"/><stop offset=".52" stop-color="#253139"/><stop offset="1" stop-color="#0c1115"/></linearGradient><linearGradient id="fog-${kind}"><stop stop-color="#c2c7c3" stop-opacity=".23"/><stop offset="1" stop-color="#778185" stop-opacity="0"/></linearGradient></defs><rect width="800" height="500" fill="url(#sky-${kind})"/><circle cx="620" cy="92" r="36" fill="#c4c6bc" opacity=".18"/><path d="M0 320 C140 275 220 340 340 300 S600 260 800 305 V500H0Z" fill="#11181c"/><path d="M0 365 C160 325 290 390 430 340 S690 330 800 360 V500H0Z" fill="#0a0f12"/>${enclave?`<g fill="#12191d" stroke="#39474e" stroke-width="3"><path d="M90 350V215l90-52 82 52v135z"/><path d="M292 350V245l70-45 74 45v105z"/><path d="M470 350V188h82v162z"/><path d="M590 350V245l55-38 63 38v105z"/><path d="M125 260h84v90h-84z" fill="#1b2429"/><path d="M502 188l10-92h20l10 92z"/></g><g stroke="#95a1a3" opacity=".22"><path d="M0 290h800"/><path d="M0 302h800"/></g>`:''}${farm?`<g fill="#131b1f"><path d="M80 360V245l105-62 110 62v115z"/><rect x="118" y="280" width="56" height="80" fill="#0b1013"/><path d="M520 360V230h54v130z"/><path d="M505 230h84l-18-58h-48z"/></g><path d="M0 380L800 335" stroke="#69787c" stroke-opacity=".18" stroke-width="18"/>`:''}${cause?`<path d="M0 330 L265 305 310 340 480 300 800 325" stroke="#202a2f" stroke-width="54" fill="none"/><path d="M280 300l48 75M468 294l-35 88" stroke="#090d0f" stroke-width="18"/><g fill="#151c20"><rect x="90" y="185" width="44" height="145"/><rect x="650" y="170" width="46" height="160"/></g>`:''}${chapel?`<g fill="#13191d"><path d="M470 360V190h150v170z"/><path d="M450 190l95-90 95 90z"/><path d="M535 105V45h20v60z"/><path d="M522 50h46v12h-46z"/><rect x="520" y="240" width="48" height="120" fill="#0a0e11"/>${kind==='warden'||kind==='title'?'<path d="M160 360V128h118v232z"/><path d="M178 128l18-96h46l18 96z"/><circle cx="219" cy="162" r="24" fill="#090d10"/>':''}</g>`:''}${map?`<g fill="#11181c" opacity=".9"><path d="M35 385L180 260 330 300 470 178 670 120 790 160v240z"/></g><path d="M90 410C160 350 205 330 265 318S390 260 446 222S585 175 690 125" fill="none" stroke="#89989a" stroke-width="8" stroke-opacity=".22" stroke-dasharray="12 14"/>`:''}<g opacity=".14" fill="url(#fog-${kind})"><ellipse cx="220" cy="280" rx="250" ry="70"/><ellipse cx="630" cy="230" rx="260" ry="58"/></g><g stroke="#c6ceca" stroke-opacity=".1">${Array.from({length:18},(_,i)=>`<path d="M${i*48-80} 0l150 500"/>`).join('')}</g></svg>`}
function hunterSvg(id){const wide=id==='vanguard'||id==='guard',coat=id==='physician';return `<svg viewBox="0 0 90 150" class="figure"><circle cx="45" cy="24" r="14" fill="#aeb6b4" opacity=".75"/><path d="M${wide?22:28} 42 Q45 30 ${wide?68:62} 42 L${wide?75:67} 112 L58 144 H48 L44 95 39 144 H28 L17 112Z" fill="${coat?'#45545a':'#303c42'}" stroke="#78868a" stroke-width="2"/><path d="M30 48L14 92M60 48l18 75" stroke="#9aa4a4" stroke-width="5" opacity=".65"/>${id==='duelist'?'<path d="M70 46l17 72" stroke="#c1c7c4" stroke-width="4"/>':''}${id==='physician'?'<path d="M45 60v28M31 74h28" stroke="#b8c0bd" stroke-width="4" opacity=".7"/>':''}</svg>`}
function enemySvg(cls){const boss=cls==='warden',husk=cls==='husk',ranged=['rifleman','spotter','bell'].includes(cls);return `<svg viewBox="0 0 100 160" class="figure enemyfig"><circle cx="50" cy="25" r="${boss?18:13}" fill="#777572" opacity=".7"/><path d="M${boss?15:25} 44 Q50 ${boss?25:34} ${boss?85:75} 44 L${boss?93:79} 122 64 155H50L46 99 39 155H25L${boss?7:18} 122Z" fill="${boss?'#3d3a3a':husk?'#454b4d':'#292f32'}" stroke="#716d6a" stroke-width="2"/>${ranged?'<path d="M57 58l38 20" stroke="#92908b" stroke-width="5"/>':''}${boss?'<path d="M18 49l-12 88M82 49l12 88" stroke="#8c8480" stroke-width="7"/>':''}</svg>`}
function debugState(){return JSON.parse(JSON.stringify(G))}
function debugSetState(x){G=JSON.parse(JSON.stringify(x));save();render()}
function debugBattle(kind='optimizer'){let loops=0;while(battle&&G.screen==='battle'&&loops++<180){const live=alive(battle.party),w=live.slice().sort((a,b)=>a.hp/a.max-b.hp/b.max)[0],target=battle.enemies[battle.target];const pri={bell:9,rifleman:8,spotter:7,servitor:6,warden:5,reaver:4,husk:3,feral:2,lurker:2,thrall:1};let best=-1,score=-1;battle.enemies.forEach((e,i)=>{if(e.hp>0&&(pri[e.cls]||0)>score){score=pri[e.cls]||0;best=i}});if(best>=0)battle.target=best;if(living('Physician')&&w&&w.hp/w.max<(kind==='conservative'?.6:.42)&&battle.resolve>=35)abilityQuiet('heal');else if(living('Vanguard')&&!battle.guard&&battle.resolve>=25&&(kind==='conservative'||kind==='optimizer'&&battle.region>=2))abilityQuiet('guard');else if(living('Duelist')&&battle.resolve>=40&&target?.hp>45)abilityQuiet('sever');else if(battle.resolve>=30)abilityQuiet('focus');if(battle&&G.screen==='battle')tick(true)}return loops<180}
function abilityQuiet(a){if(!battle)return;const b=battle,t=targetEnemy(),w=alive(b.party).sort((x,y)=>x.hp/x.max-y.hp/y.max)[0];if(a==='focus'&&b.resolve>=30&&t){b.resolve-=30;hit(t,36+Math.random()*12)}else if(a==='sever'&&b.resolve>=40&&t&&living('Duelist')){b.resolve-=40;hit(t,45);t.status.bleed=3;t.status.broken=2}else if(a==='guard'&&b.resolve>=25&&living('Vanguard')){b.resolve-=25;b.guard=3}else if(a==='heal'&&b.resolve>=35&&w&&living('Physician')){b.resolve-=35;w.hp=Math.min(w.max,w.hp+40+G.buildings.infirmary*5);w.status.bleed=0;w.status.mark=0}if(!alive(b.enemies).length)victory()}
window.Game={get state(){return G},get battle(){return battle},fresh,reset,save,render,go,objective,regionOpen,depart,startBattle,resolveEvent,tick,ability,debugBattle,debugState,debugSetState,equip,salvage,upgrade,craft,packKit,countEquipped,setCount,makeItem};
render();
})();