(()=>{
'use strict';
const CONFIG_URL='https://hiicaffetuickgnkfrvd.supabase.co/functions/v1/game-public-config';
const PREFIX='bell-beneath-ash-';
const BASE_KEY='bell-beneath-ash-p01b';
const META_KEY='bba-cloud-meta-v1';
const DEVICE_KEY='bba-device-id-v1';
let supa=null,session=null,busy=false,conflict=null,lastError='',lastSnapshot='';
function deviceId(){let v=localStorage.getItem(DEVICE_KEY);if(!v){v=crypto.randomUUID?crypto.randomUUID():String(Date.now());localStorage.setItem(DEVICE_KEY,v)}return v}
function meta(){try{return JSON.parse(localStorage.getItem(META_KEY)||'{}')}catch{return{}}}
function saveMeta(v){localStorage.setItem(META_KEY,JSON.stringify(v||{}))}
function storeKeys(){const a=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith(PREFIX))a.push(k)}return a.sort()}
function hasBaseSave(){return typeof localStorage.getItem(BASE_KEY)==='string'}
function remoteHasBase(r){return Boolean(r?.payload?.stores&&typeof r.payload.stores[BASE_KEY]==='string')}
function capture(){const stores={};for(const k of storeKeys())stores[k]=localStorage.getItem(k);return{profile_version:1,captured_at:new Date().toISOString(),stores}}
function snapshot(){const p=capture();delete p.captured_at;return JSON.stringify(p)}
function progressed(){try{const x=JSON.parse(localStorage.getItem(BASE_KEY)||'null');return Boolean(x?.started||x?.wardenDefeated||x?.clears?.some?.(Boolean))}catch{return hasBaseSave()}}
function applyPayload(p){if(!p||p.profile_version!==1||!p.stores||typeof p.stores!=='object'||typeof p.stores[BASE_KEY]!=='string')throw new Error('Cloud profile does not contain a valid base game save.');for(const k of storeKeys())localStorage.removeItem(k);for(const [k,v] of Object.entries(p.stores)){if(k.startsWith(PREFIX)&&typeof v==='string')localStorage.setItem(k,v)}}
async function getRemote(){if(!session)return null;const q=await supa.from('player_saves').select('revision,payload,server_updated_at,checksum').eq('user_id',session.user.id).maybeSingle();if(q.error)throw q.error;return q.data}
async function push(expected){if(!hasBaseSave())return null;const p=capture();const q=await supa.rpc('save_player_state',{p_payload:p,p_expected_revision:expected,p_save_version:1,p_device_id:deviceId(),p_checksum:null,p_client_updated_at:new Date().toISOString()});if(q.error)throw q.error;const r=Array.isArray(q.data)?q.data[0]:q.data;if(!r)throw new Error('No cloud revision returned.');saveMeta({user_id:session.user.id,revision:r.revision,server_updated_at:r.server_updated_at});lastSnapshot=snapshot();conflict=null;return r}
async function initialSync(){if(!session)return;busy=true;lastError='';paint();try{const r=await getRemote(),m=meta();if(!r){if(hasBaseSave())await push(0);else lastSnapshot=snapshot()}else if(!remoteHasBase(r)){if(hasBaseSave())await push(r.revision);else{saveMeta({user_id:session.user.id,revision:r.revision,server_updated_at:r.server_updated_at});lastSnapshot=snapshot()}}else if(m.user_id===session.user.id&&m.revision===r.revision){lastSnapshot=snapshot()}else if(!progressed()){applyPayload(r.payload);saveMeta({user_id:session.user.id,revision:r.revision,server_updated_at:r.server_updated_at});location.reload()}else{conflict=r}}catch(e){lastError=e?.message||String(e)}finally{busy=false;paint();renderPanel()}}
async function syncNow(){if(!session||busy||conflict||!hasBaseSave())return;busy=true;lastError='';paint();try{const r=await getRemote(),m=meta();if(!r){await push(0)}else if(!remoteHasBase(r)){await push(r.revision)}else if(m.user_id!==session.user.id||m.revision!==r.revision){conflict=r}else{await push(r.revision)}}catch(e){lastError=e?.message||String(e)}finally{busy=false;paint();renderPanel()}}
async function pollRemote(){if(!session||busy||conflict)return;try{const r=await getRemote(),m=meta();if(r&&remoteHasBase(r)&&m.user_id===session.user.id&&m.revision!=null&&m.revision!==r.revision){conflict=r;paint();renderPanel()}}catch(e){lastError=e?.message||String(e);paint()}}
async function chooseCloud(){if(!conflict||!remoteHasBase(conflict))return;applyPayload(conflict.payload);saveMeta({user_id:session.user.id,revision:conflict.revision,server_updated_at:conflict.server_updated_at});conflict=null;location.reload()}
async function chooseDevice(){if(!session||!hasBaseSave())return;busy=true;paint();try{const r=await getRemote();await push(r?r.revision:0)}catch(e){lastError=e?.message||String(e)}finally{busy=false;paint();renderPanel()}}
async function sendLink(email){const clean=String(email||'').trim().toLowerCase();if(!clean)throw new Error('Enter an email address.');const redirectTo=`${location.origin}${location.pathname}`;const q=await supa.auth.signInWithOtp({email:clean,options:{emailRedirectTo:redirectTo,shouldCreateUser:true}});if(q.error)throw q.error;return clean}
async function signOut(){await supa.auth.signOut();session=null;conflict=null;closePanel();paint()}
function label(){if(lastError)return'CLOUD ERROR';if(conflict)return'SAVE CONFLICT';if(!session)return'LOCAL SAVE';if(busy)return'SYNCING';return hasBaseSave()?'CLOUD SAVE':'CLOUD READY'}
function paint(){let b=document.querySelector('.cloud-status-bba');if(!b){b=document.createElement('button');b.className='cloud-status-bba';b.type='button';b.onclick=openPanel;document.body.append(b)}b.textContent=label()}
function closePanel(){document.querySelector('.cloud-overlay-bba')?.remove()}
function openPanel(){closePanel();const o=document.createElement('div');o.className='cloud-overlay-bba';o.innerHTML='<section class="cloud-panel-bba"><div data-cloud-panel></div></section>';o.onclick=e=>{if(e.target===o)closePanel()};document.body.append(o);renderPanel()}
function renderPanel(){const h=document.querySelector('[data-cloud-panel]');if(!h)return;if(!session){h.innerHTML='<h2>Account & Cloud Save</h2><p>Enter your email to receive a sign-in link.</p><div class="cloud-note-bba"><b>Important on iPhone/iPad</b><p>Keep the game open in Safari. In Gmail, long-press the Sign in link and choose Open in Safari. Do not let Gmail open its own browser, or that browser will not have your game save.</p></div><input data-cloud-email type="email" autocomplete="email" placeholder="you@example.com"><button data-cloud-send>Send sign-in link</button><button data-cloud-close>Close</button>';h.querySelector('[data-cloud-close]').onclick=closePanel;h.querySelector('[data-cloud-send]').onclick=async()=>{const email=h.querySelector('[data-cloud-email]').value;try{await sendLink(email);lastError='';h.querySelector('[data-cloud-send]').textContent='Link sent - open it in this same browser';paint()}catch(e){lastError=e?.message||String(e);paint();renderPanel()}};return}const m=meta();let html='<h2>Cloud Save</h2><p>Revision '+String(m.revision??'unlinked')+'</p>';if(!hasBaseSave())html+='<div class="cloud-note-bba"><b>Account connected</b><p>Your cloud account is ready. A server save will be created after the game creates its first local profile.</p></div>';if(conflict)html+='<div class="cloud-note-bba"><b>Save conflict</b><p>Nothing has been overwritten. Choose which copy should become authoritative.</p><div class="cloud-row-bba"><button data-use-cloud>Use cloud</button><button data-use-device>Use this device</button></div></div>';if(lastError)html+='<div class="cloud-note-bba">'+String(lastError)+'</div>';html+='<button data-sync-now>Sync now</button><button data-sign-out>Sign out</button><button data-cloud-close>Close</button>';h.innerHTML=html;h.querySelector('[data-cloud-close]').onclick=closePanel;h.querySelector('[data-sync-now]').onclick=syncNow;h.querySelector('[data-sign-out]').onclick=signOut;h.querySelector('[data-use-cloud]')?.addEventListener('click',chooseCloud);h.querySelector('[data-use-device]')?.addEventListener('click',chooseDevice)}
async function boot(){try{if(!window.supabase?.createClient)throw new Error('Cloud client unavailable.');const r=await fetch(CONFIG_URL);if(!r.ok)throw new Error('Cloud configuration unavailable.');const cfg=await r.json();supa=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const s=await supa.auth.getSession();session=s.data.session;supa.auth.onAuthStateChange((_event,next)=>{const old=session?.user?.id;session=next;if(next?.user?.id&&next.user.id!==old)setTimeout(initialSync,0);if(!next)conflict=null;paint();renderPanel()});paint();lastSnapshot=snapshot();if(session)await initialSync();setInterval(()=>{if(!session||busy||conflict)return;const now=snapshot();if(now!==lastSnapshot){lastSnapshot=now;setTimeout(syncNow,700)}},1500);setInterval(pollRemote,30000)}catch(e){lastError=e?.message||String(e);paint()}}
window.BellCloud={capture,getRemote,syncNow,chooseCloud,chooseDevice,pollRemote,hasBaseSave,sendLink,get session(){return session},get conflict(){return conflict},get meta(){return meta()},get lastError(){return lastError}};
boot();
})();