import { chromium } from 'playwright';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true});
const failures=[];
page.on('pageerror',e=>failures.push(`pageerror: ${e.message}`));
page.on('console',m=>{if(m.type()==='error')failures.push(`console: ${m.text()}`)});
try{
  await page.addInitScript(()=>localStorage.clear());
  await page.goto('http://127.0.0.1:8080/index.html',{waitUntil:'networkidle'});
  await page.getByText('THE BELL BENEATH ASH',{exact:false}).first().waitFor();
  await page.getByRole('button',{name:'BEGIN THE MARCH',exact:true}).click();
  await page.getByText('Open the Western Road',{exact:true}).waitFor();
  await page.getByRole('button',{name:/MARCHES/}).click();
  await page.getByRole('button',{name:/FARMSTEAD/}).click();
  await page.getByRole('button',{name:/FOCUS/}).waitFor();
  await page.evaluate(()=>{Game.battle.enemies.forEach(e=>e.hp=0);Game.tick()});
  await page.getByText('Forsaken Farmstead Cleared',{exact:true}).waitFor();
  await page.getByRole('button',{name:/SECURE \d+ DROPS/}).click();
  await page.getByText('Recovered Equipment',{exact:true}).waitFor();
  const equip=page.getByRole('button',{name:'EQUIP → Vanguard',exact:true}).first();
  await equip.click();
  await page.getByRole('button',{name:/ENCLAVE/}).last().click();
  await page.getByText('Strengthen the Hunter Hall',{exact:true}).waitFor();
  await page.getByRole('button',{name:'GO',exact:true}).click();
  await page.getByRole('button',{name:'UPGRADE',exact:true}).click();
  await page.getByText('Break the Causeway',{exact:true}).waitFor();
  await page.getByRole('button',{name:/MARCHES/}).click();
  const causeway=page.getByRole('button',{name:/CAUSEWAY/});
  if(await causeway.isDisabled())throw new Error('Causeway should be unlocked after first clear + equip + Hall Lv2.');
  if(failures.length)throw new Error(failures.join('\n'));
  console.log('0.1b mobile smoke passed: title, guided directive, first combat, multi-drop result, equip, Hall upgrade, and Causeway unlock.');
}finally{await browser.close()}
