(()=>{
'use strict';
const ROOT=document.querySelector('#app');if(!ROOT)return;
document.documentElement.classList.add('ui-v29');document.body.classList.add('polish-v29');
let lastView='',lastResources='',returnFocus=null,toastTimer=null;
function text(el){return (el?.innerText||el?.textContent||'').trim().replace(/\s+/g,' ')}
function live(){let n=document.querySelector('.v29-live');if(!n){n=document.createElement('div');n.className='v29-live';n.setAttribute('aria-live','polite');n.setAttribute('aria-atomic','true');document.body.append(n)}return n}
function toast(msg,tone='info'){if(!msg)return;let n=document.querySelector('.v29-toast');if(!n){n=document.createElement('div');n.className='v29-toast';n.setAttribute('role','status');document.body.append(n)}n.dataset.tone=tone;n.textContent=msg;n.classList.remove('show');requestAnimationFrame(()=>n.classList.add('show'));clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove('show'),1600)}
function viewName(){const v=ROOT.querySelector('.gameview,.titleview,.battleview,.resultview');if(!v)return'';if(v.classList.contains('battleview'))return'Combat';if(v.classList.contains('resultview'))return text(v.querySelector('h1,h2,b'))||'Expedition result';if(v.classList.contains('enclaveview'))return'Enclave';if(v.classList.contains('huntersview'))return'Hunters';if(v.classList.contains('mapview'))return'Ashen Marches';if(v.classList.contains('inventoryview'))return'Storehouse';if(v.classList.contains('titleview'))return'The Bell Beneath Ash';return text(v.querySelector('h1,h2,.brand'))||'Game screen'}
function decorateButtons(){ROOT.querySelectorAll('button').forEach(b=>{if(!b.hasAttribute('type'))b.type='button';if(b.disabled){b.setAttribute('aria-disabled','true');b.classList.add('v29-disabled')}else{b.removeAttribute('aria-disabled');b.classList.remove('v29-disabled')}if(!b.getAttribute('aria-label')){const t=text(b);if(t)b.setAttribute('aria-label',t.slice(0,140))}})}
function decorateDialogs(){document.querySelectorAll('.sheet,.production-sheet-v24,.kingdom-overlay-v27,.guild-overlay-v23,.contract-overlay-v21,.huntmaster-overlay-v22').forEach(d=>{if(!d.getAttribute('role'))d.setAttribute('role','dialog');d.setAttribute('aria-modal','true');if(!d.hasAttribute('tabindex'))d.tabIndex=-1})}
function combatReadability(){const battle=ROOT.querySelector('.battleview');if(!battle)return;battle.querySelectorAll('.unit,.combatant,.hunterunit,.enemyunit').forEach(u=>{const bar=u.querySelector('.hpbar [style*="width"],.hpbar > *');if(!bar)return;const m=(bar.getAttribute('style')||'').match(/width:\s*([\d.]+)%/i);if(m)u.classList.toggle('v29-critical',+m[1]<=30)});const focused=battle.querySelector('.focused,.selected,[aria-pressed="true"]');battle.classList.toggle('v29-has-focus',!!focused)}
function resourcePulse(){const hud=ROOT.querySelector('.resources');if(!hud)return;const now=text(hud);if(lastResources&&now!==lastResources){hud.classList.remove('v29-resource-change');requestAnimationFrame(()=>hud.classList.add('v29-resource-change'));setTimeout(()=>hud.classList.remove('v29-resource-change'),520)}lastResources=now}
function announceView(){const now=viewName();if(now&&now!==lastView){lastView=now;live().textContent=now;const v=ROOT.querySelector('.gameview,.titleview,.battleview,.resultview');v?.classList.add('v29-entered');setTimeout(()=>v?.classList.remove('v29-entered'),260)}}
function focusNewDialog(){const d=[...document.querySelectorAll('[role="dialog"]')].filter(x=>x.offsetParent!==null).pop();if(!d)return;if(d.dataset.v29Focused)return;d.dataset.v29Focused='1';returnFocus=document.activeElement instanceof HTMLElement?document.activeElement:null;requestAnimationFrame(()=>{const target=d.querySelector('button:not(:disabled),[tabindex="0"]')||d;target.focus?.({preventScroll:true})})}
function scan(){decorateButtons();decorateDialogs();combatReadability();resourcePulse();announceView();focusNewDialog()}
let q=false;function schedule(){if(q)return;q=true;requestAnimationFrame(()=>{q=false;scan()})}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class','disabled','aria-pressed','style']});
document.addEventListener('pointerdown',e=>{const b=e.target.closest?.('button:not(:disabled)');if(!b)return;b.classList.add('v29-pressed');setTimeout(()=>b.classList.remove('v29-pressed'),180)},true);
document.addEventListener('click',e=>{const b=e.target.closest?.('button');if(!b)return;if(b.disabled){toast('That action is currently unavailable.','locked');return}const label=text(b);if(/upgrade|craft|equip|salvage|reclaim|construct|prepare|pack kit/i.test(label))setTimeout(()=>toast(label.replace(/\s+/g,' ').slice(0,72),'success'),0)},true);
document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;const d=[...document.querySelectorAll('[role="dialog"]')].filter(x=>x.offsetParent!==null).pop();if(!d)return;const close=d.querySelector('[data-v27-close],[data-v23-close],[data-close],button[aria-label="Close"],header button:last-child');if(close&&!close.disabled){e.preventDefault();close.click();setTimeout(()=>returnFocus?.focus?.({preventScroll:true}),0)}});
scan();
window.PolishV29={scan,toast,version:29};
})();