(()=>{
'use strict';
const ROOT=document.querySelector('#app');if(!ROOT)return;
const KEY='bell-beneath-ash-strategy-v30';
const RIVALS=[
 {id:'cinders',name:'Order of Cinders',rating:1040,power:430,banner:'THE RED BELL'},
 {id:'hollow',name:'Hollow Crown',rating:1115,power:472,banner:'THE BROKEN CROWN'},
 {id:'saints',name:'Saintless Host',rating:1180,power:515,banner:'THE PALE SUN'},
 {id:'blackroad',name:'Blackroad Compact',rating:1260,power:565,banner:'THE IRON MILE'},
 {id:'vespers',name:'Vesper Dominion',rating:1350,power:620,banner:'THE LAST STAR'}
];
const OBJECTIVES=[
 {id:'gate',name:'OUTER GATE',kind:'FORTIFICATION',base:110,score:120},
 {id:'tower',name:'SIGNAL TOWER',kind:'CONTROL',base:128,score:145},
 {id:'keep',name:'WAR KEEP',kind:'COMMAND',base:150,score:185}
];
function fresh(){return {version:1,realmName:'Ashen March',banner:'Bell Wardens',prestige:1000,influence:0,wins:0,losses:0,army:{levy:60,guard:18,scouts:12},war:{phase:'idle',opponent:null,prepUntil:0,endAt:0,attacks:3,score:0,enemyScore:0,assignments:{},log:[],rewarded:false}}}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x?.version===1?Object.assign(fresh(),x):fresh()}catch{return fresh()}}
let S=load();function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function game(){return window.Game?.state||null}
function kingdom(){return window.KingdomV27?.bonuses?.()||{hp:0,atk:0,economy:0,resolve:0,warDefense:0,warStrike:0}}
function guild(){return window.GuildV23?.load?.()||{formed:false,name:'No Guild',level:0,wins:0,losses:0}}
function armyCap(){const k=window.KingdomV27?.load?.();const land=k?.plots?.filter(p=>p.reclaimed).length||1;const hall=game()?.buildings?.hall||1;return 90+land*30+hall*20}
function armySize(){return S.army.levy+S.army.guard+S.army.scouts}
function armyPower(){const b=kingdom(),g=guild();return Math.round(S.army.levy*1.4+S.army.guard*2.2+S.army.scouts*1.7+(b.warStrike||0)+(b.warDefense||0)+(g.level||0)*12)}
function standing(){if(S.influence>=500)return'CINDER DOMINION';if(S.influence>=250)return'WESTERN HOLD';if(S.influence>=100)return'FORTIFIED MARCH';if(S.influence>=35)return'RECLAIMED WARD';return'ASHEN ENCLAVE'}
function tier(){const r=S.prestige;if(r>=1400)return'RELIC';if(r>=1250)return'GILDED';if(r>=1125)return'IRON';if(r>=1025)return'ASH';return'UNRANKED'}
function rankRows(){const rows=RIVALS.map(r=>({name:r.name,rating:r.rating,power:r.power,player:false}));rows.push({name:S.realmName,rating:S.prestige,power:armyPower(),player:true});return rows.sort((a,b)=>b.rating-a.rating).map((x,i)=>({...x,rank:i+1}))}
function rival(id){return RIVALS.find(x=>x.id===id)||RIVALS[0]}
function selectedHunterPower(name){const h=game()?.hunters?.find(x=>x.name===name);if(!h)return 0;const st=window.Game?.hunterStats?.(h)||{hp:h.hp,atk:h.atk};return Math.round((st.hp||0)/10+(st.atk||0)*2+(h.lv||1)*8)}
function train(type,count=10){if(!['levy','guard','scouts'].includes(type))return false;const g=window.Game?.debugState?.();if(!g)return false;const costs={levy:{coin:18,iron:4},guard:{coin:14,iron:10},scouts:{coin:22,iron:6}}[type];if(armySize()+count>armyCap()||g.coin<costs.coin||g.iron<costs.iron)return false;g.coin-=costs.coin;g.iron-=costs.iron;window.Game.debugSetState(g);S.army[type]+=count;save();render();return true}
function scheduleWar(id){if(S.war.phase!=='idle'&&S.war.phase!=='results')return;const r=rival(id);S.war={phase:'prep',opponent:r.id,prepUntil:Date.now()+30000,endAt:0,attacks:3,score:0,enemyScore:0,assignments:{},log:[`War declared against ${r.name}. Preparation window opened.`],rewarded:false};save();render()}
function assign(obj,hunter){if(S.war.phase!=='prep')return;for(const k of Object.keys(S.war.assignments)){if(S.war.assignments[k]===hunter)delete S.war.assignments[k]}S.war.assignments[obj]=hunter;save();render()}
function beginWar(force=false){if(S.war.phase!=='prep'||Object.keys(S.war.assignments).length<3)return false;if(!force&&Date.now()<S.war.prepUntil)return false;S.war.phase='war';S.war.endAt=Date.now()+180000;S.war.log.unshift('War window opened. Three coordinated attacks available.');save();render();return true}
function strike(id){if(S.war.phase!=='war'||S.war.attacks<=0)return;const o=OBJECTIVES.find(x=>x.id===id),r=rival(S.war.opponent);if(!o)return;const hunter=S.war.assignments[id]||'Vanguard',k=kingdom(),g=guild();const attack=armyPower()*.32+selectedHunterPower(hunter)+(k.warStrike||0)+(g.level||0)*8;const defense=o.base+(r.power-400)*.28;const roll=.88+Math.random()*.24;const success=attack*roll>=defense;const gained=Math.round(o.score*(success?1:.42));const enemyRaw=62+Math.random()*54+(r.power-armyPower())*.12;const denied=(k.warDefense||0)*.7+S.army.guard*.18;const enemy=Math.max(20,Math.round(enemyRaw-denied));S.war.score+=gained;S.war.enemyScore+=enemy;S.war.attacks--;S.war.log.unshift(`${hunter} struck ${o.name}: ${success?'BREACHED':'CONTESTED'} · +${gained}.`);if(S.war.attacks<=0)resolveWar();save();render()}
function resolveWar(){if(S.war.phase!=='war')return;const r=rival(S.war.opponent);S.war.phase='results';const win=S.war.score>=S.war.enemyScore;if(win){S.wins++;S.prestige+=Math.max(18,Math.round((r.rating-S.prestige)*.12+34));S.influence+=35}else{S.losses++;S.prestige=Math.max(850,S.prestige-18);S.influence+=8}S.war.log.unshift(win?'Victory. Enemy territory yields influence.':'Defeat. The surviving host returns to the Enclave.');save()}
function claim(){if(S.war.phase!=='results'||S.war.rewarded)return;const win=S.war.score>=S.war.enemyScore,g=window.Game?.debugState?.();if(g){g.coin+=win?95:38;g.iron+=win?28:10;g.salvage+=win?18:7;window.Game.debugSetState(g)}S.war.rewarded=true;save();render()}
function resetWar(){if(S.war.phase==='results'&&S.war.rewarded){S.war={phase:'idle',opponent:null,prepUntil:0,endAt:0,attacks:3,score:0,enemyScore:0,assignments:{},log:[],rewarded:false};save();render()}}
function formatTime(ms){const n=Math.max(0,Math.ceil(ms/1000));return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`}
function warHtml(){const w=S.war;if(w.phase==='idle')return `<section class="realm-war-v30 idle"><header><small>SCHEDULED WAR</small><b>Choose a Rival Power</b><span>Declare war, prepare three strike teams, then attack during the war window.</span></header><div class="realm-rivals-v30">${RIVALS.slice(0,3).map(r=>`<button data-v30-schedule="${r.id}"><small>${r.rating} PRESTIGE · ${r.power} PWR</small><b>${r.name}</b><span>${r.banner}</span></button>`).join('')}</div></section>`;
const r=rival(w.opponent);if(w.phase==='prep'){const ready=Object.keys(w.assignments).length===3;return `<section class="realm-war-v30 prep"><header><small>PHASE I · PREPARATION</small><b>${esc(S.realmName)} vs ${r.name}</b><span>War opens in <strong data-v30-countdown>${formatTime(w.prepUntil-Date.now())}</strong></span></header><div class="realm-objectives-v30">${OBJECTIVES.map(o=>`<article><small>${o.kind}</small><b>${o.name}</b><span>DEF ${Math.round(o.base+(r.power-400)*.28)} · ${o.score} score</span><div>${['Vanguard','Duelist','Physician'].map(h=>`<button data-v30-assign="${o.id}" data-hunter="${h}" class="${w.assignments[o.id]===h?'selected':''}">${h}</button>`).join('')}</div></article>`).join('')}</div><button class="realm-primary-v30" data-v30-begin ${ready?'':'disabled'}>${ready?'BEGIN WHEN WAR WINDOW OPENS':'ASSIGN ALL THREE HUNTERS'}</button></section>`}
if(w.phase==='war')return `<section class="realm-war-v30 active"><header><small>PHASE II · WAR</small><b>${esc(S.realmName)} vs ${r.name}</b><span>${w.attacks} coordinated attacks remain</span></header><div class="realm-score-v30"><b>${w.score}</b><span>WAR SCORE</span><b>${w.enemyScore}</b></div><div class="realm-targets-v30">${OBJECTIVES.map(o=>`<button data-v30-strike="${o.id}" ${w.attacks<=0?'disabled':''}><small>${o.kind}</small><b>${o.name}</b><span>${w.assignments[o.id]} · ${o.score} max</span></button>`).join('')}</div><div class="realm-log-v30">${w.log.slice(0,4).map(x=>`<span>${esc(x)}</span>`).join('')}</div></section>`;
const win=w.score>=w.enemyScore;return `<section class="realm-war-v30 results ${win?'win':'loss'}"><header><small>PHASE III · RESULTS</small><b>${win?'WAR VICTORY':'WAR DEFEAT'}</b><span>${S.war.score} · ${S.war.enemyScore} ${r.name}</span></header><div class="realm-result-grid-v30"><div><small>PRESTIGE</small><b>${S.prestige}</b></div><div><small>INFLUENCE</small><b>${S.influence}</b></div><div><small>RECORD</small><b>${S.wins}-${S.losses}</b></div></div><button class="realm-primary-v30" data-v30-claim ${w.rewarded?'disabled':''}>${w.rewarded?'WAR REWARDS CLAIMED':'CLAIM WAR REWARDS'}</button>${w.rewarded?'<button data-v30-reset>RETURN TO WAR BOARD</button>':''}</section>`}
function rankingsHtml(){return `<section class="realm-rankings-v30"><header><small>REGIONAL LADDER</small><b>Realm Rankings</b><span>Persistent local prototype standings against rival powers.</span></header>${rankRows().map(x=>`<article class="${x.player?'player':''}"><i>#${x.rank}</i><div><b>${esc(x.name)}</b><span>${x.player?tier():'RIVAL POWER'} · ${x.power} PWR</span></div><em>${x.rating}</em></article>`).join('')}</section>`}
function armyHtml(){const cap=armyCap(),size=armySize();return `<section class="realm-army-v30"><header><small>PERSISTENT FORCE</small><b>War Host</b><span>${size}/${cap} troops · ${armyPower()} total war power</span></header><div class="realm-army-grid-v30"><article><small>LEVY</small><b>${S.army.levy}</b><span>mass assault</span><button data-v30-train="levy">TRAIN +10 · ◈18 ⚒4</button></article><article><small>GUARD</small><b>${S.army.guard}</b><span>war defense</span><button data-v30-train="guard">TRAIN +10 · ◈14 ⚒10</button></article><article><small>SCOUTS</small><b>${S.army.scouts}</b><span>strike support</span><button data-v30-train="scouts">TRAIN +10 · ◈22 ⚒6</button></article></div></section>`}
function realmSummary(){const g=guild(),k=window.KingdomV27?.load?.(),land=k?.plots?.filter(p=>p.reclaimed).length||1,built=k?.plots?.filter(p=>p.building).length||0;return `<section class="realm-summary-v30"><div><small>REALM</small><b>${esc(S.realmName)}</b><span>${standing()} · ${tier()} TIER</span></div><div><small>DOMAIN</small><b>${land}/6</b><span>${built} districts built</span></div><div><small>WAR HOST</small><b>${armyPower()}</b><span>${armySize()}/${armyCap()} troops</span></div><div><small>GUILD</small><b>${g.formed?esc(g.name):'UNFORMED'}</b><span>LV ${g.level||0} · ${g.wins||0}-${g.losses||0}</span></div></section>`}
function close(){document.querySelector('.realm-overlay-v30')?.remove()}
function render(){close();const ov=document.createElement('div');ov.className='realm-overlay-v30';ov.innerHTML=`<section class="realm-shell-v30"><header class="realm-head-v30"><div><small>WAR COUNCIL · V30</small><b>${esc(S.realmName)}</b><span>${S.banner} · ${standing()}</span></div><button data-v30-close>×</button></header>${realmSummary()}<main class="realm-main-v30"><div>${armyHtml()}${warHtml()}</div>${rankingsHtml()}</main><footer class="realm-links-v30"><button data-v30-domain>MANAGE DOMAIN</button><button data-v30-guild>OPEN GUILD HALL</button></footer></section>`;document.body.append(ov);
ov.querySelector('[data-v30-close]')?.addEventListener('click',close);ov.addEventListener('click',e=>{if(e.target===ov)close()});ov.querySelectorAll('[data-v30-train]').forEach(b=>b.addEventListener('click',()=>train(b.dataset.v30Train)));ov.querySelectorAll('[data-v30-schedule]').forEach(b=>b.addEventListener('click',()=>scheduleWar(b.dataset.v30Schedule)));ov.querySelectorAll('[data-v30-assign]').forEach(b=>b.addEventListener('click',()=>assign(b.dataset.v30Assign,b.dataset.hunter)));ov.querySelector('[data-v30-begin]')?.addEventListener('click',()=>beginWar(false));ov.querySelectorAll('[data-v30-strike]').forEach(b=>b.addEventListener('click',()=>strike(b.dataset.v30Strike)));ov.querySelector('[data-v30-claim]')?.addEventListener('click',claim);ov.querySelector('[data-v30-reset]')?.addEventListener('click',resetWar);ov.querySelector('[data-v30-domain]')?.addEventListener('click',()=>{close();window.KingdomV27?.open?.()});ov.querySelector('[data-v30-guild]')?.addEventListener('click',()=>{close();window.GuildV23?.open?.()});}
function decorateNav(){ROOT.querySelectorAll('.bottomnav').forEach(nav=>{if(nav.querySelector('[data-v30-realm]'))return;const b=document.createElement('button');b.dataset.v30Realm='';b.innerHTML='<i>♛</i><span>REALM</span>';b.addEventListener('click',render);nav.append(b)})}
function decorateEnclave(){ROOT.querySelectorAll('.enclaveview').forEach(v=>{if(v.querySelector('.realm-card-v30'))return;const world=v.querySelector('.worldscene');if(!world)return;const card=document.createElement('button');card.className='realm-card-v30';card.innerHTML=`<small>${standing()}</small><b>${esc(S.realmName)}</b><span>${armyPower()} PWR · ${S.prestige} PRESTIGE · ${S.wins}-${S.losses} WAR</span>`;card.addEventListener('click',render);world.append(card)})}
function tick(){if(S.war.phase==='prep'&&Date.now()>=S.war.prepUntil&&Object.keys(S.war.assignments).length===3){beginWar(true)}if(S.war.phase==='war'&&Date.now()>=S.war.endAt&&S.war.attacks>0){while(S.war.attacks>0){S.war.enemyScore+=55;S.war.attacks--}resolveWar();render()}document.querySelectorAll('[data-v30-countdown]').forEach(x=>x.textContent=formatTime(S.war.prepUntil-Date.now()))}
function scan(){decorateNav();decorateEnclave()}
let q=false;function schedule(){if(q)return;q=true;requestAnimationFrame(()=>{q=false;scan()})}
new MutationObserver(schedule).observe(ROOT,{childList:true,subtree:true});scan();setInterval(tick,1000);
window.StrategyV30={open:render,load:()=>JSON.parse(JSON.stringify(S)),save:next=>{S=Object.assign(fresh(),next||{});save();return StrategyV30.load()},reset:()=>{S=fresh();save()},armyPower,rankRows,beginWar,resolveWar,debugSetWarPhase:(p)=>{S.war.phase=p;save()}};
})();