import { chromium } from 'playwright';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true});
const failures=[];
page.on('pageerror',e=>failures.push(`pageerror: ${e.message}`));
page.on('console',m=>{if(m.type()==='error')failures.push(`console: ${m.text()}`)});
try{
  await page.addInitScript(()=>localStorage.clear());
  await page.goto('http://127.0.0.1:8080/index.html',{waitUntil:'networkidle'});
  await page.locator('button[data-begin]').waitFor();
  await page.locator('button[data-begin]').click();
  await page.evaluate(()=>{
    const s=Game.debugState();
    s.started=true;
    s.screen='map';
    s.clears=[1,1,1,0];
    s.buildings.hall=3;
    s.buildings.infirmary=3;
    s.crafted=1;
    Game.debugSetState(s);
    Game.startBattle(3,{});
  });
  await page.locator('.battleview').waitFor();
  await page.waitForFunction(()=>document.querySelector('.battleview')?.dataset.v8==='1');
  const scene=page.locator('.battlescene');
  if(!await scene.evaluate(el=>el.classList.contains('zone-warden')&&el.classList.contains('v15-warden-art')))throw new Error('Warden arena presentation class was not applied.');
  const bg=await scene.evaluate(el=>getComputedStyle(el).backgroundImage);
  if(!bg.includes('battle-warden-v1.svg'))throw new Error('Illustrated Warden arena did not load.');
  if(await page.locator('.enemyformation .battleunit').count()!==3)throw new Error('Warden encounter must render boss plus two servitors.');
  if(await page.locator('.enemyformation .v15-boss').count()!==1)throw new Error('Penitent Warden boss art was not bound.');
  if(await page.locator('.enemyformation .v15-servitor').count()!==2)throw new Error('Bellbound Servitor art was not bound.');
  const bossArt=await page.locator('.enemyformation .v15-boss').evaluate(el=>getComputedStyle(el).getPropertyValue('--unit-art'));
  if(!bossArt.includes('enemy-penitent-warden-v1.svg'))throw new Error('Penitent Warden illustration source missing.');
  const servitorArt=await page.locator('.enemyformation .v15-servitor').evaluateAll(els=>els.map(el=>getComputedStyle(el).getPropertyValue('--unit-art')));
  if(servitorArt.some(x=>!x.includes('enemy-bellbound-servitor-v1.svg')))throw new Error('A servitor illustration source is missing.');
  await page.screenshot({path:'warden-v15-preview.png',fullPage:true});
  await page.evaluate(()=>{Game.battle.enemies.forEach(e=>e.hp=0);Game.tick()});
  await page.locator('.resultview').waitFor();
  await page.locator('.resultart .scene-warden').waitFor();
  const resultBg=await page.locator('.resultart').evaluate(el=>getComputedStyle(el).backgroundImage);
  if(!resultBg.includes('battle-warden-v1.svg'))throw new Error('Boss victory did not preserve Warden arena art.');
  if(!(await page.locator('.resultcopy h1').innerText()).includes('THE BELL FALLS SILENT'))throw new Error('Boss victory copy missing.');
  const state=await page.evaluate(()=>Game.debugState());
  if(!state.wardenDefeated||state.clears[3]<1)throw new Error('Boss victory did not persist campaign completion.');
  if(!state.inventory.some(x=>x.name==='Warden’s Penitent Blade'))throw new Error('Guaranteed Warden relic was not awarded.');
  await page.screenshot({path:'warden-v15-result.png',fullPage:true});
  if(failures.length)throw new Error(failures.join('\n'));
  console.log('V15 Warden smoke passed: arena, boss art, servitor art, victory state and guaranteed relic are functional.');
}finally{await browser.close()}
